function t121_setHeight(recid){var rec=document.getElementById('rec'+recid);var videoBlock=document.getElementById('youtubeiframe'+recid);var videoParent=videoBlock?videoBlock.parentNode:null;var videoWidth=videoBlock?videoBlock.offsetWidth:0;var videoHeight=videoWidth*0.5625;if(videoBlock)videoBlock.style.height=videoHeight+'px';if(videoParent)videoParent.style.height=videoHeight+'px';var videoLazy=rec?rec.querySelector('.t-video-lazyload'):null;if(videoLazy){var iframeLazy=videoLazy.querySelector('iframe');var heightLazy=videoLazy.offsetWidth*0.5625;videoLazy.style.height=heightLazy+'px';if(iframeLazy)iframeLazy.style.height=heightLazy+'px';setTimeout(function(){videoBlock=document.getElementById('youtubeiframe'+recid);videoWidth=videoBlock?videoBlock.offsetWidth:0;if(videoBlock)videoBlock.style.height=(videoWidth*0.5625)+'px'},200)}}
function t142_checkSize(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var button=rec.querySelector('.t142__submit');if(!button)return;var buttonStyle=getComputedStyle(button,null);var buttonPaddingTop=parseInt(buttonStyle.paddingTop)||0;var buttonPaddingBottom=parseInt(buttonStyle.paddingBottom)||0;var buttonHeight=button.clientHeight-(buttonPaddingTop+buttonPaddingBottom)+5;var textHeight=button.scrollHeight;if(buttonHeight<textHeight){button.classList.add('t142__submit-overflowed')}}
function t282_showMenu(recid){var el=$("#rec"+recid);el.find('.t282__burger, .t282__menu__item:not(".tooltipstered"):not(".t282__menu__item_submenu"), .t282__overlay').click(function(){if($(this).is(".t282__menu__item.tooltipstered, .t794__tm-link, .t978__tm-link, .t966__tm-link")){return}
$('body').toggleClass('t282_opened');el.find('.t282__menu__container, .t282__overlay').toggleClass('t282__closed');var height=el.find(".t282__container").get(0).getBoundingClientRect().height;el.find(".t282__menu__container").css({'top':height});t282_highlight(recid)});el.find('.t282').bind('clickedAnchorInTooltipMenu',function(){$('body').removeClass('t282_opened');$('#rec'+recid+' .t282__menu__container, #rec'+recid+' .t282__overlay').addClass('t282__closed')});if(el.find('.t-menusub__link-item')){el.find('.t-menusub__link-item').on('click',function(){$('body').removeClass('t282_opened');$('#rec'+recid+' .t282__menu__container, #rec'+recid+' .t282__overlay').addClass('t282__closed')})}}
function t282_changeSize(recid){var el=$("#rec"+recid);var bottomheight=el.find(".t282__menu__container");var headerheight=el.find(".t282__container");var menu=bottomheight.height()+headerheight.height();var win=$(window).height();if(menu>win){$("#nav"+recid).addClass('t282__menu_static')}else{$("#nav"+recid).removeClass('t282__menu_static')}}
function t282_changeBgOpacityMenu(recid){var window_width=$(window).width();var record=$("#rec"+recid);record.find(".t282__container__bg").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacity=el.attr("data-bgopacity");var bgopacity_afterscroll=el.attr("data-bgopacity2");var menu_shadow=el.attr("data-menu-shadow");if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacity_afterscroll!="0"&&bgopacity_afterscroll!="0.0"){el.css('box-shadow',menu_shadow)}else{el.css('box-shadow','none')}}else{el.css("background-color",bgcolor);if(bgopacity!="0"&&bgopacity!="0.0"){el.css('box-shadow',menu_shadow)}else{el.css('box-shadow','none')}}})}
function t282_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname===""){pathname="/"}
if(hash.substr(hash.length-1)=="/"){hash=hash.slice(0,-1)}
if(hash==""){hash="/"}
$("#rec"+recid).find(".t282__menu a").removeClass("t-active");$(".t282__menu a[href='"+url+"']").addClass("t-active");$(".t282__menu a[href='"+url+"/']").addClass("t-active");$(".t282__menu a[href='"+pathname+"']").addClass("t-active");$(".t282__menu a[href='/"+pathname+"']").addClass("t-active");$(".t282__menu a[href='"+pathname+"/']").addClass("t-active");$(".t282__menu a[href='/"+pathname+"/']").addClass("t-active");$(".t282__menu a[href='"+hash+"']").addClass("t-active");$(".t282__menu a[href='/"+hash+"']").addClass("t-active");$(".t282__menu a[href='"+hash+"/']").addClass("t-active");$(".t282__menu a[href='/"+hash+"/']").addClass("t-active")}
function t282_appearMenu(recid){var window_width=$(window).width();$(".t282").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!==""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}
function t367_createCookie(name,value,days){if(days){var date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));var expires="; expires="+date.toGMTString()}
else var expires="";document.cookie=name+"="+value+expires+"; path=/"}
function t367_readCookie(name){var nameEQ=name+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' ')c=c.substring(1,c.length);if(c.indexOf(nameEQ)==0)return c.substring(nameEQ.length,c.length)}
return null}
function t367_autoInit(recid){var winWidth=$(window).width();var screenMin=$('#rec'+recid).attr("data-screen-min");var screenMax=$('#rec'+recid).attr("data-screen-max");if(typeof screenMin!=='undefined'){if(winWidth<parseInt(screenMin,10)){return!1}}
if(typeof screenMax!=='undefined'){if(winWidth>parseInt(screenMax,10)){return!1}}
var el=$('#rec'+recid).find('.t367__opener');var name=el.attr('data-cookie-name');var time=el.attr('data-cookie-time');var value="t367cookie";var cookie=t367_readCookie(name);var delay=el.attr('data-trigger-time');var delaytime=delay*1000;if(cookie){$("#rec"+recid+" .t367").html("")}else if(el.length){setTimeout(function(){el.trigger('click');if(el.get(0)&&el.get(0).getAttribute('href')){el.get(0).click()}
$("#rec"+recid+" .t367").html("");t367_createCookie(name,value,time)},delaytime)}}
function t390_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t390');if(!container)return;rec.setAttribute('data-animationappear','off');rec.style.opacity=1;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var analitics=popup.getAttribute('data-track-popup');var popupCloseBtn=popup.querySelector('.t-popup__close');var hrefs=rec.querySelectorAll('a[href*="#"]');if(popupTooltipHook){var recBlocks=document.querySelectorAll('.r');for(var i=0;i<recBlocks.length;i++){recBlocks[i].addEventListener('click',function(event){var target=event.target;var href=target.closest('a[href="'+popupTooltipHook+'"]')?target:!1;if(!href)return;event.preventDefault();t390_showPopup(recId);t390_resizePopup(recId);t390__lazyLoad();if(analitics){Tilda.sendEventToStatistics(analitics,popupTooltipHook)}})}}
popup.addEventListener('scroll',t_throttle(function(){t390__lazyLoad()}));popup.addEventListener('click',function(event){if(event.target===this)t390_closePopup()});popupCloseBtn.addEventListener('click',t390_closePopup);for(var i=0;i<hrefs.length;i++){hrefs[i].addEventListener('click',function(){var url=this.getAttribute('href');if(!url||url.substring(0,7)!='#price:'){t390_closePopup();if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){document.body.classList.add('t-body_popupshowed')},300)}}})}
var curPath=window.location.pathname;var curFullPath=window.location.origin+curPath;var isAndroid=/(android)/i.test(navigator.userAgent);if(isAndroid){var selects='a[href^="#"]:not([href="#"]):not([href^="#price"]):not([href^="#popup"]):not([href^="#prodpopup"]):not([href^="#order"]):not([href^="#!"]),'+'a[href^="'+curPath+'#"]:not([href*="#!/tproduct/"]):not([href*="#!/tab/"]):not([href*="#popup"]),'+'a[href^="'+curFullPath+'#"]:not([href*="#!/tproduct/"]):not([href*="#!/tab/"]):not([href*="#popup"])';var selectors=rec.querySelectorAll(selects);for(var i=0;i<selectors.length;i++){selectors[i].addEventListener('click',function(event){event.preventDefault();var hash=this.hash.trim();if(window.location.hash){setTimeout(function(){window.location.href=hash},50)}})}}}
function t390_showPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t390');if(!container)return;var popup=rec.querySelector('.t-popup');var popupContainer=popup.querySelector('.t-popup__container');var documentBody=document.body;popup.style.display='block';setTimeout(function(){popupContainer.classList.add('t-popup__container-animated');popup.classList.add('t-popup_show')},50);documentBody.classList.add('t-body_popupshowed');documentBody.classList.add('t390__body_popupshowed');document.addEventListener('keydown',t390_escClosePopup)}
function t390_escClosePopup(event){if(event.key==='Escape')t390_closePopup()}
function t390_closePopup(){var popupAll=document.querySelectorAll('.t-popup');document.body.classList.remove('t-body_popupshowed');for(var i=0;i<popupAll.length;i++){popupAll[i].classList.remove('t-popup_show')}
setTimeout(function(){var popupHide=document.querySelectorAll('.t-popup:not(.t-popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);document.removeEventListener('keydown',t390_escClosePopup)}
function t390_resizePopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var popupContainer=rec.querySelector('.t-popup__container');if(!popupContainer)return;var popupStyle=getComputedStyle(popupContainer,null);var popupPaddingTop=parseInt(popupStyle.paddingTop)||0;var popupPaddingBottom=parseInt(popupStyle.paddingBottom)||0;var popupHeight=popupContainer.clientHeight-(popupPaddingTop+popupPaddingBottom);if(popupHeight>(window.innerHeight-120)){popupContainer.classList.add('t-popup__container-static')}else{popupContainer.classList.remove('t-popup__container-static')}}
function t390_sendPopupEventToStatistics(popupName){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupName.substring(0,7)=='#popup:'){popupName=popupName.substring(7)}
virtPage+=popupName;virtTitle+=popupName;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t390__lazyLoad(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t400_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t400');if(!container)return;var button=rec.querySelector('.t400__submit');var hideBackText=button.getAttribute('data-hide-back-text');var showMoreText=button.textContent;button.addEventListener('click',function(){if(hideBackText&&button.classList.contains('t400__submit_hide-back')){t400_alltabs_updateContent(recId);button.classList.remove('t400__submit_hide-back');if(button.classList.contains('t400__submit-overflowed')){button.innerHTML='<span class="t400__text">'+showMoreText+'</span>'}else{button.innerHTML=showMoreText}
var zeroBlocks=document.querySelectorAll('.t396');for(var i=0;i<zeroBlocks.length;i++){t400__triggerEvent(zeroBlocks[i],'displayChanged')}
return}
var recIds=button.getAttribute('data-hidden-rec-ids').split(',');for(var i=0;i<recIds.length;i++){var recShowBlock=document.getElementById('rec'+recIds[i]);if(recShowBlock){recShowBlock.classList.remove('t400__off');recShowBlock.style.opacity='';var videos=recShowBlock.querySelectorAll('.t-video-lazyload');if(videos.length>0){var video=videos[0];if(video.closest('.t121')||video.closest('.t223')||video.closest('.t230')||video.closest('.t368')){t400_updateVideoLazyLoad(videos)}}
var selectors=recShowBlock.querySelectorAll('.t-feed, .t-store, .t-store__product-snippet, .t117, .t121, .t132, .t223, .t226, .t228, .t229, .t230, .t268, .t279, .t341, .t346, .t347, .t349, .t351, .t353, .t384, .t385, .t386, .t396, .t400, .t404, .t409, .t410, .t412, .t418, .t422, .t425, .t428, .t433, .t456, .t477, .t478, .t480, .t486, .t498, .t504, .t506, .t509, .t511, .t517, .t518, .t519, .t520, .t527, .t531, .t532, .t533, .t538, .t539, .t544, .t545, .t552, .t554, .t570, .t577, .t592, .t598, .t599, .t601, .t604, .t605, .t609, .t615, .t616, .t650, .t659, .t670, .t675, .t686, .t688, .t694, .t698, .t700, .t726, .t728, .t730, .t734, .t738, .t740, .t744, .t754, .t760, .t762, .t764, .t774, .t776, .t778, .t780, .t786, .t798, .t799, .t801, .t813, .t814, .t822, .t826, .t827, .t829, .t842, .t843, .t849, .t850, .t851, .t856, .t858, .t859, .t860, .t881, .t889, .t899, .t902, .t905, .t912, .t923, .t937, .t958, .t959, .t979, .t982, .t983, .t989, .t994, .t1000, .t1003');for(var j=0;j<selectors.length;j++){t400__triggerEvent(selectors[j],'displayChanged')}}}
if(hideBackText){button.classList.add('t400__submit_hide-back');if(button.classList.contains('t400__submit-overflowed')){button.innerHTML='<span class="t400__text">'+hideBackText+'</span>'}else{button.innerHTML=hideBackText}}else{rec.classList.add('t400__off');rec.style.display='none'}
if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}});t400_alltabs_updateContent(recId);t400_checkSize(recId);$(container).bind('displayChanged',function(){t400_checkSize(recId)})}
function t400_alltabs_updateContent(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var button=rec.querySelector('.t400__submit');if(!button)return;var recIds=button.getAttribute('data-hidden-rec-ids').split(',');for(var i=0;i<recIds.length;i++){var recHideBlock=document.getElementById('rec'+recIds[i]);if(!recHideBlock)return;recHideBlock.setAttribute('data-animationappear','off');recHideBlock.setAttribute('data-connect-with-tab','yes');recHideBlock.classList.add('t400__off')}}
function t400_checkSize(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var button=rec.querySelector('.t400__submit');if(!button)return;var buttonStyle=getComputedStyle(button,null);var buttonPaddingTop=parseInt(buttonStyle.paddingTop)||0;var buttonPaddingBottom=parseInt(buttonStyle.paddingBottom)||0;var buttonHeight=button.clientHeight-(buttonPaddingTop+buttonPaddingBottom);var buttonScrollHeight=button.scrollHeight;if(buttonHeight<buttonScrollHeight){var buttonText=button.textContent;button.classList.add('t400__submit-overflowed');button.innerHTML='<span class="t400__text">'+buttonText+'</span>'}}
function t400_updateVideoLazyLoad(videos){setTimeout(function(){for(var i=0;i<videos.length;i++){var video=videos[i];var videoHeight=video.getAttribute('data-videolazy-height')||'100%';if(videoHeight.indexOf('vh')!==-1){videoHeight='100%'}
var videoId=video.getAttribute('data-videolazy-id').trim();var blockId=video.getAttribute('data-blocklazy-id')||'';var videoTwoId=video.getAttribute('data-videolazy-two-id')||'';if(videoTwoId)videoTwoId='_'+videoTwoId+'_';if(video.getAttribute('data-videolazy-type')==='youtube'){var iframes=video.querySelectorAll('iframe');for(var j=0;j<iframes.length;j++){var oldFrame=iframes[j];if(oldFrame&&oldFrame.parentNode)oldFrame.parentNode.removeChild(oldFrame)}
var iframe=document.createElement('iframe');iframe.id='youtubeiframe'+videoTwoId+blockId;iframe.width='100%';iframe.height=videoHeight;iframe.src='//www.youtube.com/embed/'+videoId+'?rel=0&fmt=18&html5=1&showinfo=0';iframe.setAttribute('frameborder','0');iframe.setAttribute('allowfullscreen','');video.insertBefore(iframe,video.firstChild)}}})}
function t400__triggerEvent(el,eventName){var event;if(typeof window.CustomEvent==='function'){event=new CustomEvent(eventName)}else if(document.createEvent){event=document.createEvent('HTMLEvents');event.initEvent(eventName,!0,!1)}else if(document.createEventObject){event=document.createEventObject();event.eventType=eventName}
event.eventName=eventName;if(el.dispatchEvent){el.dispatchEvent(event)}else if(el.fireEvent){el.fireEvent('on'+event.eventType,event)}else if(el[eventName]){el[eventName]()}else if(el['on'+eventName]){el['on'+eventName]()}
if(t400__checkJqueryEvent(el,eventName)){$(el).trigger(eventName)}}
function t400__checkJqueryEvent(element,eventName){var events=$._data(element,'events')||!1;var isEvent=!1;if(events){for(var key in events){if(key===eventName){isEvent=!0;break}}}
return isEvent}
function t431_init(recId){var table=document.querySelector('#rec'+recId+' .t431 .t431__table');if(!table)return;var dataPart1=document.querySelector('#rec'+recId+' .t431 .t431__data-part1');var dataPart2=document.querySelector('#rec'+recId+' .t431 .t431__data-part2');var tableHead=t431__escapeHTML(dataPart1&&dataPart1.innerHTML||'');var tableBody=t431__escapeHTML(dataPart2&&dataPart2.innerHTML||'');var tableColSize=table.getAttribute('data-table-width');var hasTargetBlank=table.getAttribute('data-target-blank');var tHead=t431_parseData(tableHead);var tBody=t431_parseData(tableBody);var colSize=t431_parseData(tableColSize);var maxColNum=t431__findMaxRowLengthInTable(tHead,tBody);var colWidth=t431__setColumnsWidth(colSize,maxColNum,recId);var html='';if(tHead){html+=t431__generateTable(tHead,'th',hasTargetBlank,colWidth,maxColNum)}
if(tBody){html+=t431__generateTable(tBody,'td',hasTargetBlank,colWidth,maxColNum)}
table.insertAdjacentHTML('beforeend',html)}
function t431__findMaxRowLengthInTable(arrayHead,arrayData){var headMaxLength=0;var dataMaxLength=0;if(arrayHead){headMaxLength=t431__findMaxRowLengInArray(arrayHead)}
if(arrayData){dataMaxLength=t431__findMaxRowLengInArray(arrayData)}
if(dataMaxLength>headMaxLength){return dataMaxLength}else{return headMaxLength}}
function t431__escapeHTML(string){var html=string.replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&').replace(/&nbsp;/g,' ');var result='';var allowedTags='';['b','i','u','ul','li','ol','br','img','s','sub','sup','span','hr','pre','code','mark','strong','small'].forEach(function(value){allowedTags+=':not('+value+')'});var allowedAttrs=['alt','class','title','id','src','style','width','height','data-replace-key'];var parseHTML=function(str){var fakeDOM=document.implementation.createHTMLDocument('fake');fakeDOM.body.innerHTML=str;return fakeDOM.body.childNodes};var createdStructure;if(parseHTML(html)){createdStructure=parseHTML(html)}else{createdStructure=[]}
for(var i=0;i<createdStructure.length;i++){var element=createdStructure[i];if(element!==allowedTags){if(element.nodeType!==3&&element.nodeType!==8){var temp=document.createElement(element.tagName);allowedAttrs.forEach(function(value){if(element.getAttribute(value)!==null){temp.setAttribute(value,element.getAttribute(value).replace(/javascript:/gi,''))}});temp.textContent=element.textContent;result+=temp.outerHTML}else{result+=element.textContent}}}
return result}
function t431__findMaxRowLengInArray(currentArray){var maxLength=0;for(var i=0;i<currentArray.length;i++){if(currentArray[i].length>maxLength){maxLength=currentArray[i].length}}
return maxLength}
function t431__setColumnsWidth(colWidth,colsNumber,recId){if(colWidth){return colWidth[0]}else{var tableWidth=document.querySelector('#rec'+recId+' .t431 .t-container .t-col');var computedWidth=parseFloat(getComputedStyle(tableWidth,null).width.replace('px',''));return(computedWidth/colsNumber+'px')}}
function t431__generateTable(arrayValues,colTag,hasTargetBlank,colWidth,maxColNumber){var html='';var tag='';if(colTag=='td'){tag='tbody'}else{tag='thead'}
html+='<'+tag+' class="t431__'+tag+'">';for(var i=0;i<arrayValues.length;i++){if(colTag=='td'){if((i+1)%2>0){html+='<tr class="t431__oddrow">'}else{html+='<tr class="t431__evenrow">'}}else{html+='<tr>'}
var addingCols=0;if(arrayValues[i].length<maxColNumber){addingCols=maxColNumber-arrayValues[i].length}
for(var j=0;j<(arrayValues[i].length+addingCols);j++){if(arrayValues[i][j]){var currentWidth='';if(Array.isArray(colWidth)&&colWidth[j]){currentWidth=colWidth[j].myText}else{currentWidth=colWidth}
var colWithAttr='';if(colTag=='td'){colWithAttr='<td class="t431__td t-text" width="'+currentWidth+'">'}else{colWithAttr='<th class="t431__th t-title" width="'+currentWidth+'">'}
if(arrayValues[i][j].myHref){var targetBlank='';if(hasTargetBlank){targetBlank='target="_blank"'}
var linkWithAttr='';var linkCloseTag='';if(arrayValues[i][j].myHrefType=='link'){linkWithAttr='<a href="'+arrayValues[i][j].myHref+'"'+targetBlank+'>';linkCloseTag='</a>'}else{linkWithAttr='<div class="t431__btnwrapper"><a href="'+arrayValues[i][j].myHref+'"'+targetBlank+' class="t-btn t-btn_sm"><table style="width:100%; height:100%"><tr><td>';linkCloseTag='</td></tr></table></a></div>'}
html+=colWithAttr+linkWithAttr+arrayValues[i][j].myText+linkCloseTag+'</'+colTag+'>'}else{html+=colWithAttr+arrayValues[i][j].myText+'</'+colTag+'>'}}else{html+='<'+colTag+' class="t431__'+colTag+'" width="'+currentWidth+'">'+'</'+colTag+'>'}}
html+='</tr>'}
html+='</'+tag+'>';return html}
function t431_parseData(data){if(data!==''&&typeof data!='undefined'){data=t431__addBrTag(data);var arrayTable=[];var arrayRow=[];var currentItem={myText:'',myHref:'',myHrefType:''};var hasLink='';var hasLinkWithSpace='';var hasButton='';var hasButtonWithSpace='';var endLine='';for(var i=0;i<data.length;i++){if(data[i]==';'&&!(data.slice(i-4,i)=='&lt;'||data.slice(i-4,i)=='&gt;'||data.slice(i-5,i)=='&amp;'||data.slice(i-6,i)=='&nbsp;')){arrayRow.push(currentItem);currentItem={myText:'',myHref:''};hasLink='';hasLinkWithSpace='';hasButton='';hasButtonWithSpace=''}else{if(hasLink=='link='||hasLinkWithSpace==' link='||hasButton=='button='||hasButtonWithSpace==' button='){if(currentItem.myHref===''&&hasLink==='link='){currentItem.myText=currentItem.myText.slice(0,-5);currentItem.myHrefType='link'}else if(currentItem.myHref===''&&hasLinkWithSpace===' link='){currentItem.myText=currentItem.myText.slice(0,-6);currentItem.myHrefType='link'}else if(currentItem.myHref===''&&hasButton==='button='){currentItem.myText=currentItem.myText.slice(0,-7);currentItem.myHrefType='btn'}else if(currentItem.myHref===''&&hasButtonWithSpace===' button='){currentItem.myText=currentItem.myText.slice(0,-8);currentItem.myHrefType='btn'}
currentItem.myHref+=(data[i])}else{currentItem.myText+=(data[i]);hasLink=t431__checkSubstr('link=',hasLink,data[i]);hasLinkWithSpace=t431__checkSubstr(' link=',hasLinkWithSpace,data[i]);hasButton=t431__checkSubstr('button=',hasButton,data[i]);hasButtonWithSpace=t431__checkSubstr(' button=',hasButtonWithSpace,data[i])}
endLine=t431__checkSubstr('<br />',endLine,data[i]);if(endLine=='<br />'){if(currentItem.myHref){currentItem.myHref=currentItem.myHref.slice(0,-6)}else{currentItem.myText=currentItem.myText.slice(0,-6)}
arrayRow.push(currentItem);arrayTable.push(arrayRow);currentItem={myText:'',myHref:''};hasLink='';hasLinkWithSpace='';hasButton='';hasButtonWithSpace='';arrayRow=[]}}}
if(arrayRow.length>0||currentItem.myText!==''){if(currentItem!==''){arrayRow.push(currentItem)}
arrayTable.push(arrayRow)}}
return arrayTable}
function t431__checkSubstr(targetSubstr,currentSubstr,curSymbol){if(!currentSubstr&&curSymbol==targetSubstr[0]){return curSymbol}else if(currentSubstr){for(var i=0;i<(targetSubstr.length-1);i++){if(currentSubstr[currentSubstr.length-1]==targetSubstr[i]&&curSymbol==targetSubstr[i+1]){return(currentSubstr+=curSymbol)}}}}
function t431__addBrTag(oldStringItem){var newStringItem='';if(oldStringItem){for(var i=0;i<oldStringItem.length;i++){if(oldStringItem[i]=='\n'||oldStringItem[i]=='\r'){newStringItem+='<br />'}else{newStringItem+=oldStringItem[i]}}}
return newStringItem.replace(/&nbsp;/g,' ')}
function t431_createTable(recId,tableHead,tableData,tableColSize,hasTargetBlank,buttonStyles,tdStyles,thStyles,oddRowStyles,evenRowStyles){var arrayColSize=t431_parseData(tableColSize);var tableArrayHead=t431_parseData(tableHead);var tableArrayData=t431_parseData(tableData);var tableMaxColNumber=t431__findMaxRowLengthInTable(tableArrayHead,tableArrayData);var tableColWidth=t431__setColumnsWidth(arrayColSize,tableMaxColNumber,recId);if(tableColWidth[0].myText&&tableColWidth[0].myText[tableColWidth[0].myText.length-1]=='%'){for(var i=0;i<tableColWidth.length;i++){tableColWidth[i].myText=tableColWidth[i].myText.slice(0,-1);tableColWidth[i].myText+='vw'}}
var tableContainer=document.querySelector('#rec'+recId+' .t431 .t-container .t431__table');var tableHTML='';if(tableArrayHead){tableHTML+=t431__generateHtml(recId,tableArrayHead,'th',hasTargetBlank,tableColWidth,buttonStyles,thStyles,null,null,tableMaxColNumber)}
tableContainer.insertAdjacentHTML('afterbegin',tableHTML);tableHTML='';if(tableArrayData){tableHTML+=t431__generateHtml(recId,tableArrayData,'td',hasTargetBlank,tableColWidth,buttonStyles,tdStyles,oddRowStyles,evenRowStyles,tableMaxColNumber)}
tableContainer.insertAdjacentHTML('afterbegin',tableHTML)}
function t431__generateHtml(recId,arrayValues,colTag,hasTargetBlank,colWidth,buttonStyles,colstyles,oddRowStyles,evenRowStyles,maxcolnumber){var partHTML='';var headOrBodyTag;if(colTag=='td'){headOrBodyTag='tbody'}else{headOrBodyTag='thead'}
partHTML+='<'+headOrBodyTag+' class="t431__'+headOrBodyTag+'">';var firstBodyRowStyle='';if(document.querySelector('#rec'+recId+' .t431 .t-container .t431__thead th').length>0&&document.querySelector('#rec'+recId+' .t431 .t-container .t431__thead th').style.borderBottomWidth!='0'){firstBodyRowStyle='border-top: 0 !important;'}
for(var i=0;i<arrayValues.length;i++){if(colTag=='td'){if((i+1)%2>0){partHTML+='<tr class="t431__oddrow"'+'style="'+oddRowStyles+'">'}else{partHTML+='<tr class="t431__evenrow"'+'style="'+evenRowStyles+'">'}}else{partHTML+='<tr>'}
var htmlAddingCols=0;if(arrayValues[i].length<maxcolnumber){htmlAddingCols=maxcolnumber-arrayValues[i].length}
for(var j=0;j<(arrayValues[i].length+htmlAddingCols);j++){if(arrayValues[i][j]){var currentWidthHTML;if(Array.isArray(colWidth)&&colWidth[j]){currentWidthHTML=colWidth[j].myText}else{currentWidthHTML=colWidth}
var colWithAttrHTML;if(i==0&&colTag=='td'){colWithAttrHTML='<'+colTag+' class="t431__'+colTag+'" style="width:'+currentWidthHTML+';'+colstyles+firstBodyRowStyle+'">'}else{colWithAttrHTML='<'+colTag+' class="t431__'+colTag+'" style="width:'+currentWidthHTML+';'+colstyles+'">'}
if(arrayValues[i][j].myHref){var targetBlankHTML='';if(hasTargetBlank){var targetBlankHTML='target="_blank"'}
var linkWithAttrHTML;var linkCloseTagHTML;if(arrayValues[i][j].myHrefType=='link'){linkWithAttrHTML='<a href="'+arrayValues[i][j].myHref+'"'+targetBlankHTML+'>';linkCloseTagHTML='</a>'}else{linkWithAttrHTML='<div class="t431__btnwrapper"><a href="'+arrayValues[i][j].myHref+'"'+targetBlankHTML+' class="t-btn t-btn_sm" style="'+buttonStyles+'"><table style="width:100%; height:100%;"><tr><td>';linkCloseTagHTML='</td></tr></table></a></div>'}
partHTML+=colWithAttrHTML+linkWithAttrHTML+arrayValues[i][j].myText+linkCloseTagHTML+'</'+colTag+'>'}else{partHTML+=colWithAttrHTML+arrayValues[i][j].myText+'</'+colTag+'>'}}else{partHTML+='<'+colTag+' class="t431__'+colTag+'" style="width:'+currentWidthHTML+';'+colstyles+'">'+'</'+colTag+'>'}}
partHTML+='</tr>'}
partHTML+='</'+headOrBodyTag+'>';return partHTML}
function t450_showMenu(recid){var el=$('#rec'+recid);$('body').addClass('t450__body_menushowed');el.find('.t450').addClass('t450__menu_show');el.find('.t450__overlay').addClass('t450__menu_show');$('.t450').bind('clickedAnchorInTooltipMenu',function(){t450_closeMenu()});el.find('.t450__overlay, .t450__close, a[href*="#"]').click(function(){var url=$(this).attr('href');if(typeof url!='undefined'&&url!=''&&(url.substring(0,7)=='#price:'||url.substring(0,9)=='#submenu:')){return}
if($(this).is('.tooltipstered, .t-menusub__target-link, .t794__tm-link, .t966__tm-link, .t978__tm-link')){return}
t450_closeMenu()});$(document).keydown(function(e){if(e.keyCode===27){$('body').removeClass('t390__body_popupshowed');$('.t390').removeClass('t390__popup_show')}});el.find('.t-menu__link-item').each(function(){var $this=$(this);if($this.hasClass('t966__tm-link')){$this.on('click',function(){setTimeout(function(){t450_checkSize(recid)},300)})}
if($this.hasClass('t978__tm-link')){$this.on('click',function(){t450_checkSize(recid);el.find(".t978__menu-link").on('click',function(){t450_checkSize(recid)})})}});t450_highlight()}
function t450_closeMenu(){$('body').removeClass('t450__body_menushowed');$('.t450').removeClass('t450__menu_show');$('.t450__overlay').removeClass('t450__menu_show')}
function t450_checkSize(recid){var el=$('#rec'+recid).find('.t450');var windowheight=$(window).height()-80;setTimeout(function(){var contentheight=el.find(".t450__top").height()+el.find(".t450__rightside").height();if(contentheight>windowheight){el.addClass('t450__overflowed');el.find(".t450__container").css('height','auto')}else{el.removeClass('t450__overflowed');el.find(".t450__container").css('height','')}})}
function t450_appearMenu(recid){var el=$('#rec'+recid);var burger=el.find(".t450__burger_container");burger.each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");var hideoffset=el.attr("data-hideoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.hasClass('t450__beforeready')){el.finish();el.removeClass("t450__beforeready")}}else{el.stop();el.addClass("t450__beforeready")}}
if(hideoffset!=""){if(hideoffset.indexOf('vh')>-1){hideoffset=Math.floor((window.innerHeight*(parseInt(hideoffset)/100)))}
hideoffset=parseInt(hideoffset,10);if($(window).scrollTop()+$(window).height()>=$(document).height()-hideoffset){if(!el.hasClass('t450__beforeready')){el.finish();el.addClass("t450__beforeready")}}else{if(appearoffset!=""){if($(window).scrollTop()>=appearoffset){el.stop();el.removeClass("t450__beforeready")}}else{el.stop();el.removeClass("t450__beforeready")}}}})}
function t450_initMenu(recid){var el=$('#rec'+recid).find('.t450');var hook=el.attr('data-tooltip-hook');if(hook!==''){$('.r').on('click','a[href="'+hook+'"]',function(e){t450_closeMenu();t450_showMenu(recid);t450_checkSize(recid);e.preventDefault()})}
$('#rec'+recid).find('.t450__burger_container').click(function(e){t450_closeMenu();t450_showMenu(recid);t450_checkSize(recid)});if(window.isMobile){$('#rec'+recid).find('.t-menu__link-item').each(function(){var $this=$(this);if($this.hasClass('t450__link-item_submenu')){$this.on('click',function(){t450_checkSize(recid)})}})}
$(window).on('resize',function(){t450_checkSize(recid)})}
function t450_highlight(){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t450__menu a").removeClass("t-active");$(".t450__menu a[href='"+url+"']").addClass("t-active");$(".t450__menu a[href='"+url+"/']").addClass("t-active");$(".t450__menu a[href='"+pathname+"']").addClass("t-active");$(".t450__menu a[href='/"+pathname+"']").addClass("t-active");$(".t450__menu a[href='"+pathname+"/']").addClass("t-active");$(".t450__menu a[href='/"+pathname+"/']").addClass("t-active");if(hash!==""){$(".t450__menu a[href='"+hash+"']").addClass("t-active")}}
function t461_setLogoPadding(recid){if($(window).width()>980){var t461__menu=$('#rec'+recid+' .t461');var t461__logo=t461__menu.find('.t461__logowrapper');var t461__leftpart=t461__menu.find('.t461__leftwrapper');var t461__rightpart=t461__menu.find('.t461__rightwrapper');t461__leftpart.css("padding-right",t461__logo.width()/2+50);t461__rightpart.css("padding-left",t461__logo.width()/2+50)}}
function t461_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t461__list_item a[href='"+url+"']").addClass("t-active");$(".t461__list_item a[href='"+url+"/']").addClass("t-active");$(".t461__list_item a[href='"+pathname+"']").addClass("t-active");$(".t461__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t461__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t461__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t461_checkAnchorLinks(recid){if($(window).width()>=960){var t461_navLinks=$("#rec"+recid+" .t461__desktoplist .t461__list_item a:not(.tooltipstered)[href*='#']");if(t461_navLinks.length>0){t461_catchScroll(t461_navLinks)}}}
function t461_catchScroll(t461_navLinks){var t461_clickedSectionId=null,t461_sections=new Array(),t461_sectionIdTonavigationLink=[],t461_interval=100,t461_lastCall,t461_timeoutId;t461_navLinks=$(t461_navLinks.get().reverse());t461_navLinks.each(function(){var t461_cursection=t461_getSectionByHref($(this));if(typeof t461_cursection.attr("id")!="undefined"){t461_sections.push(t461_cursection)}
t461_sectionIdTonavigationLink[t461_cursection.attr("id")]=$(this)});t461_updateSectionsOffsets(t461_sections);t461_sections.sort(function(a,b){return b.attr("data-offset-top")-a.attr("data-offset-top")});$(window).bind('resize',t_throttle(function(){t461_updateSectionsOffsets(t461_sections)},200));$('.t461').bind('displayChanged',function(){t461_updateSectionsOffsets(t461_sections)});setInterval(function(){t461_updateSectionsOffsets(t461_sections)},5000);t461_highlightNavLinks(t461_navLinks,t461_sections,t461_sectionIdTonavigationLink,t461_clickedSectionId);t461_navLinks.click(function(){var t461_clickedSection=t461_getSectionByHref($(this));if(!$(this).hasClass("tooltipstered")&&typeof t461_clickedSection.attr("id")!="undefined"){t461_navLinks.removeClass('t-active');$(this).addClass('t-active');t461_clickedSectionId=t461_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t461_now=new Date().getTime();if(t461_lastCall&&t461_now<(t461_lastCall+t461_interval)){clearTimeout(t461_timeoutId);t461_timeoutId=setTimeout(function(){t461_lastCall=t461_now;t461_clickedSectionId=t461_highlightNavLinks(t461_navLinks,t461_sections,t461_sectionIdTonavigationLink,t461_clickedSectionId)},t461_interval-(t461_now-t461_lastCall))}else{t461_lastCall=t461_now;t461_clickedSectionId=t461_highlightNavLinks(t461_navLinks,t461_sections,t461_sectionIdTonavigationLink,t461_clickedSectionId)}})}
function t461_updateSectionsOffsets(sections){$(sections).each(function(){var t461_curSection=$(this);t461_curSection.attr("data-offset-top",t461_curSection.offset().top)})}
function t461_getSectionByHref(curlink){var t461_curLinkValue=curlink.attr("href").replace(/\s+/g,'');if(t461_curLinkValue[0]=='/'){t461_curLinkValue=t461_curLinkValue.substring(1)}
if(curlink.is('[href*="#rec"]')){return $(".r[id='"+t461_curLinkValue.substring(1)+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+t461_curLinkValue.substring(1)+"']")}}
function t461_highlightNavLinks(t461_navLinks,t461_sections,t461_sectionIdTonavigationLink,t461_clickedSectionId){var t461_scrollPosition=$(window).scrollTop(),t461_valueToReturn=t461_clickedSectionId;if(t461_sections.length!=0&&t461_clickedSectionId==null&&t461_sections[t461_sections.length-1].attr("data-offset-top")>(t461_scrollPosition+300)){t461_navLinks.removeClass('t-active');return null}
$(t461_sections).each(function(e){var t461_curSection=$(this),t461_sectionTop=t461_curSection.attr("data-offset-top"),t461_id=t461_curSection.attr('id'),t461_navLink=t461_sectionIdTonavigationLink[t461_id];if(((t461_scrollPosition+300)>=t461_sectionTop)||(t461_sections[0].attr("id")==t461_id&&t461_scrollPosition>=$(document).height()-$(window).height())){if(t461_clickedSectionId==null&&!t461_navLink.hasClass('t-active')){t461_navLinks.removeClass('t-active');t461_navLink.addClass('t-active');t461_valueToReturn=null}else{if(t461_clickedSectionId!=null&&t461_id==t461_clickedSectionId){t461_valueToReturn=null}}
return!1}});return t461_valueToReturn}
function t461_setPath(){}
function t461_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t461").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t461").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t461_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t461").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t461_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t461").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t461_createMobileMenu(recid){var el=$("#rec"+recid);var menu=el.find(".t461");var burger=el.find(".t461__mobile");burger.on('click',function(e){$(menu).fadeToggle(300);$(this).toggleClass("t461_opened")});$(window).on('resize',t_throttle(function(){if($(window).width()>980){$(menu).fadeIn(0)}}))}
function t478_setHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var sizer=rec.querySelector('.t478__sizer');if(!sizer)return;var sizerStyle=getComputedStyle(sizer,null);var sizerPaddingTop=parseInt(sizerStyle.paddingTop);var sizerPaddingBottom=parseInt(sizerStyle.paddingBottom);var sizerPaddingLeft=parseInt(sizerStyle.paddingLeft);var sizerPaddingRight=parseInt(sizerStyle.paddingRight);var sizerHeight=sizer.clientHeight-(sizerPaddingTop+sizerPaddingBottom);var sizerWidth=sizer.clientWidth-(sizerPaddingLeft+sizerPaddingRight);var ratio=sizerWidth/sizerHeight;var wrappers=rec.querySelectorAll('.t478__blockimg, .t478__textwrapper');if(sizerHeight!==window.innerHeight){for(var i=0;i<wrappers.length;i++){wrappers[i].style.height=(sizerWidth/ratio)+'px'}}}
function t527_setHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t527');if(!container)return;var images=rec.querySelectorAll('.t527__bgimg');if(!images[0])return;var imageWidth=images[0].getAttribute('data-image-width');var imageHeight=images[0].getAttribute('data-image-height');var imageRatio=imageHeight/imageWidth;var imagePadding=imageRatio*100;for(var i=0;i<images.length;i++){images[i].style.paddingBottom=imagePadding+'%'}}
function t544_setHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t544');if(!container)return;var sizer=rec.querySelector('.t544__sizer');var sizerStyle=getComputedStyle(sizer,null);var sizerPaddingLeft=parseInt(sizerStyle.paddingLeft)||0;var sizerPaddingRight=parseInt(sizerStyle.paddingRight)||0;var sizerPaddingTop=parseInt(sizerStyle.paddingTop)||0;var sizerPaddingBottom=parseInt(sizerStyle.paddingBottom)||0;var sizerHeight=sizer.clientHeight-(sizerPaddingTop+sizerPaddingBottom);var sizerWidth=sizer.clientWidth-(sizerPaddingLeft+sizerPaddingRight);var sizerRatio=sizerWidth/sizerHeight;var elements=rec.querySelectorAll('.t544__blockimg, .t544__textwrapper');var elementStyle=getComputedStyle(elements[0],null);var elementPaddingLeft=parseInt(elementStyle.paddingLeft)||0;var elementPaddingRight=parseInt(elementStyle.paddingRight)||0;var elementWidth=elements[0].clientWidth-(elementPaddingLeft+elementPaddingRight);var maxHeight=elementWidth/sizerRatio;if(sizerHeight!==window.innerHeight){for(var i=0;i<elements.length;i++){elements[i].style.height=maxHeight+'px'}}}
function t576_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t576');if(!container)return;var items=rec.querySelectorAll('.t576__item');var firstItem=items[0];var lastItem=items[items.length-1];for(var i=0;i<items.length;i++){var item=items[i];var circle=item.querySelector('.t576__circle');var img=item.querySelector('.t576__img');var imgHeight=0;if(img)imgHeight=img.offsetHeight;if(circle)circle.style.top=(imgHeight+15)+'px'}
if(firstItem){var firstLine=firstItem.querySelector('.t576__line');var firstImg=firstItem.querySelector('.t576__img');var firstImgHeight=0;if(firstImg)firstImgHeight=firstImg.offsetHeight;if(firstLine)firstLine.style.top=(firstImgHeight+15)+'px'}
if(lastItem){var lastLine=lastItem.querySelector('.t576__line');var lastImg=lastItem.querySelector('.t576__img');var lastImgHeight=0;if(lastImg)lastImgHeight=lastImg.offsetHeight;if(lastLine)lastLine.style.height=(lastImgHeight+20)+'px'}}
function t585_init(recid){var el=$('#rec'+recid);var toggler=el.find(".t585__header");var accordion=el.find('.t585__accordion');if(accordion){accordion=accordion.attr('data-accordion')}else{accordion="false"}
var scrolltoExpand=el.find('.t585__accordion').attr('data-scroll-to-expanded');toggler.click(function(){if(accordion==="true"){toggler.not(this).removeClass("t585__opened").next().slideUp()}
$(this).toggleClass("t585__opened");var _this=$(this);$(this).next().slideToggle(function(){if(scrolltoExpand==="true"){$('html, body').animate({scrollTop:$(_this).offset().top||el.offset().top},300)}});if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}
function t607_init(recid){t607_checkAnchorLinks(recid)}
function t607_checkAnchorLinks(recid){if($(window).width()>=960){var t607_navLinks=$("#rec"+recid+" .t607__list_item a:not(.tooltipstered)[href*='#']");if(t607_navLinks.length>0){t607_catchScroll(t607_navLinks)}}}
function t607_catchScroll(t607_navLinks){var t607_clickedSectionId=null,t607_sections=new Array(),t607_sectionIdTonavigationLink={},t607_interval=100,t607_lastCall,t607_timeoutId;t607_navLinks=$(t607_navLinks.get().reverse());t607_navLinks.each(function(){var t607_cursection=t607_getSectionByHref($(this));if(typeof t607_cursection.attr("id")!="undefined"){t607_sections.push(t607_cursection)}
t607_sectionIdTonavigationLink[t607_cursection.attr("id")]=$(this)});t607_highlightNavLinks(t607_navLinks,t607_sections,t607_sectionIdTonavigationLink,t607_clickedSectionId);setTimeout(function(){t607_highlightNavLinks(t607_navLinks,t607_sections,t607_sectionIdTonavigationLink,t607_clickedSectionId)},1000);$(document).keydown(function(e){var t607_direction="";switch(e.which){case 38:t607_direction="top";break;case 40:t607_direction="bottom";break;case 33:t607_direction="top";break;case 34:t607_direction="bottom";break;default:return}
if(t607_direction!=""){var t607_curActiveSectionId=t607_getSectionByHref(t607_navLinks.filter(".t-active")).attr("id"),t607_newActiveSectionIndex=$.map(t607_sections,function(obj,index){if(obj.attr("id")==t607_curActiveSectionId&&t607_direction=="top"){return index+1}
if(obj.attr("id")==t607_curActiveSectionId&&t607_direction=="bottom"){return index-1}});var t607_newActiveSection=t607_sections[t607_newActiveSectionIndex[0]];if(typeof t607_newActiveSection=="undefined"){return}
t607_navLinks.removeClass('t-active');var $root=$('html, body'),t607_offsetTop=$(".t607").attr("data-offset-top");t607_sectionIdTonavigationLink[t607_newActiveSection.attr("id")].addClass('t-active');t607_clickedSectionId=t607_newActiveSection.attr("id");if(typeof t607_offsetTop!="undefined"){$root.animate({scrollTop:t607_newActiveSection.offset().top-t607_offsetTop},500)}
else{$root.animate({scrollTop:t607_newActiveSection.offset().top},500)}}});t607_navLinks.click(function(){if(!$(this).hasClass("tooltipstered")){t607_navLinks.removeClass('t-active');var t607_clickedSection=t607_getSectionByHref($(this));var $root=$('html, body');var t607_offsetTop=$(".t607").attr("data-offset-top");if(t607_clickedSection.length===0)return;if(!$(this).hasClass("t-active")){t607_clickedSectionId=t607_clickedSection.attr("id")}
t607_sectionIdTonavigationLink[t607_clickedSection.attr("id")].addClass('t-active');if(typeof t607_offsetTop!="undefined"){$root.animate({scrollTop:t607_clickedSection.offset().top-t607_offsetTop},500)}else{$root.animate({scrollTop:t607_clickedSection.offset().top},500)}
return!1}});$(window).scroll(function(){var t607_now=new Date().getTime();if(t607_lastCall&&t607_now<(t607_lastCall+t607_interval)){clearTimeout(t607_timeoutId);t607_timeoutId=setTimeout(function(){t607_lastCall=t607_now;t607_clickedSectionId=t607_highlightNavLinks(t607_navLinks,t607_sections,t607_sectionIdTonavigationLink,t607_clickedSectionId)},t607_interval-(t607_now-t607_lastCall))}else{t607_lastCall=t607_now;t607_clickedSectionId=t607_highlightNavLinks(t607_navLinks,t607_sections,t607_sectionIdTonavigationLink,t607_clickedSectionId)}})}
function t607_getSectionByHref(curlink){var curLinkValue=(curlink.attr('href')||'').replace(/\s+/g,'').replace(/.*#/,'');if(curlink.is('[href*="#rec"]')){return $(".r[id='"+curLinkValue+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+curLinkValue+"']")}}
function t607_highlightNavLinks(t607_navLinks,t607_sections,t607_sectionIdTonavigationLink,t607_clickedSectionId){var t607_scrollPosition=$(window).scrollTop(),t607_valueToReturn=t607_clickedSectionId;if(typeof t607_sections[t607_sections.length-2]!="undefined"&&t607_sections[t607_sections.length-2].offset().top<=$(window).height()/2&&t607_scrollPosition==0){t607_navLinks.removeClass('t-active');t607_navLink=t607_sectionIdTonavigationLink[t607_sections[t607_sections.length-1].attr("id")];t607_navLink.addClass('t-active');return null}
$(t607_sections).each(function(e){var t607_curSection=$(this),t607_sectionTop=t607_curSection.offset().top,t607_id=t607_curSection.attr('id'),t607_navLink=t607_sectionIdTonavigationLink[t607_id];if((t607_scrollPosition+$(window).height()/2)>=t607_sectionTop||(t607_sections[0].attr("id")==t607_id&&$(window).scrollTop()>=$(document).height()-$(window).height())){if(t607_clickedSectionId==null&&!t607_navLink.hasClass('t-active')){t607_navLinks.removeClass('t-active');t607_navLink.addClass('t-active');t607_valueToReturn=null}else{if(t607_clickedSectionId!=null&&t607_id==t607_clickedSectionId){t607_valueToReturn=null}}
return!1}});return t607_valueToReturn}
function t696_onSuccess(t696_form){var t696_inputsWrapper=t696_form.find('.t-form__inputsbox');var t696_inputsHeight=t696_inputsWrapper.height();var t696_inputsOffset=t696_inputsWrapper.offset().top;var t696_inputsBottom=t696_inputsHeight+t696_inputsOffset;var t696_targetOffset=t696_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t696_target=t696_targetOffset-200}else{var t696_target=t696_targetOffset-100}
if(t696_targetOffset>$(window).scrollTop()||($(document).height()-t696_inputsBottom)<($(window).height()-100)){t696_inputsWrapper.addClass('t696__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t696_target},400);setTimeout(function(){t696_inputsWrapper.addClass('t696__inputsbox_hidden')},400)}
var successurl=t696_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t698_fixcontentheight(id){var el=$("#rec"+id);var hcover=el.find(".t-cover").height();var hcontent=el.find("div[data-hook-content]").outerHeight();if(hcontent>300&&hcover<hcontent){var hcontent=hcontent+120;if(hcontent>1000){hcontent+=100}
console.log('auto correct cover height: '+hcontent);el.find(".t-cover").height(hcontent);el.find(".t-cover__filter").height(hcontent);el.find(".t-cover__carrier").height(hcontent);el.find(".t-cover__wrapper").height(hcontent);el.find(".t-cover__container").height(hcontent);if($isMobile==!1){setTimeout(function(){var divvideo=el.find(".t-cover__carrier");if(divvideo.find('iframe').length>0){console.log('correct video from cover_fixcontentheight');setWidthHeightYoutubeVideo(divvideo,hcontent+'px')}},2000)}}}
function t698_onSuccess(t698_form){var t698_inputsWrapper=t698_form.find('.t-form__inputsbox');var t698_inputsHeight=t698_inputsWrapper.height();var t698_inputsOffset=t698_inputsWrapper.offset().top;var t698_inputsBottom=t698_inputsHeight+t698_inputsOffset;var t698_targetOffset=t698_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t698_target=t698_targetOffset-200}else{var t698_target=t698_targetOffset-100}
if(t698_targetOffset>$(window).scrollTop()||($(document).height()-t698_inputsBottom)<($(window).height()-100)){t698_inputsWrapper.addClass('t698__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t698_target},400);setTimeout(function(){t698_inputsWrapper.addClass('t698__inputsbox_hidden')},400)}
var successurl=t698_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t796_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t796');if(!container)return;var windowWidth=window.innerWidth;var screenMin=rec.getAttribute('data-screen-min');var screenMax=rec.getAttribute('data-screen-max');if(screenMin&&windowWidth<parseInt(screenMin,10))return!1;if(screenMax&&windowWidth>parseInt(screenMax,10))return!1;var shapeBorder=rec.querySelector('.t796__shape-border');var shapeRecId=container.getAttribute('data-shape-rec-ids');if(shapeRecId){shapeRecId=shapeRecId.split(',');for(var i=0;i<shapeRecId.length;i++){var shapeId=shapeRecId[i];var currentRec=document.querySelector('#rec'+shapeId);var currentShape=shapeBorder.cloneNode(!0);t796_setColor(rec,currentShape);t796_addDivider(currentRec,currentShape)}}else{var excludesBlocks=[215,316,390,651,702,706,708,750,756,766,825,862,868,943];var excludes='';for(var i=0;i<excludesBlocks.length;i++){excludes+=':not([data-record-type=\''+excludesBlocks[i]+'\']),'}
if(excludes.slice(-1)===','){excludes=excludes.slice(0,-1)}
var recs=[];if(shapeBorder.classList.contains('t796__shape-border_top')||shapeBorder.classList.contains('t796__shape-border_top-flip')){recs=t796__nextAll(rec,excludes)}
if(shapeBorder.classList.contains('t796__shape-border_bottom')||shapeBorder.classList.contains('t796__shape-border_bottom-flip')){recs=t796__prevAll(rec,excludes)}
if(recs.length!==0){var currentShape=shapeBorder.cloneNode(!0);t796_setColor(rec,currentShape);t796_addDivider(recs[0],currentShape)}}}
function t796_setColor(rec,shape){if(shape.getAttribute('data-fill-color'))return;var nearestBlock;if(shape.classList.contains('t796__shape-border_bottom')||shape.classList.contains('t796__shape-border_bottom-flip')){var nextBlock=rec.nextElementSibling;if(nextBlock){nearestBlock=nextBlock.matches('.r')?nextBlock:!1}}else{var prevBlock=rec.previousElementSibling;if(prevBlock){nearestBlock=prevBlock.matches('.r')?prevBlock:!1}}
if(!nearestBlock)return;var fillColor=nearestBlock.getAttribute('data-bg-color');if(!fillColor)return;shape.querySelector('.t796__svg').style.fill=fillColor}
function t796_addDivider(rec,shape){if(!rec)return;rec.setAttribute('data-animationappear','off');rec.classList.remove('r_hidden');var cover=rec.querySelector('.t-cover');var zeroBlock=rec.querySelector('.t396');if(cover||zeroBlock){if(cover){var showLayers=cover.querySelectorAll('.t557__snow-layer');if(showLayers.length>0)shape.style.zIndex=1;var coverFilter=cover.querySelector('.t-cover__filter');if(coverFilter)coverFilter.insertAdjacentElement('afterend',shape)}
if(zeroBlock){zeroBlock.insertAdjacentElement('afterend',shape);rec.style.position='relative';var zeroFilter=zeroBlock.querySelector('.t396__filter');if(zeroFilter){var zIndex=1;var zeroArtboard=zeroBlock.querySelector('.t396__artboard');var isVisible=zeroArtboard.style.overflow==='visible';if(!isVisible)zIndex=99;shape.style.zIndex=zIndex}}
shape.style.display='block'}else{var wrapper=rec;var recordType=parseInt(rec.getAttribute('data-record-type'));if(!wrapper)return!0;wrapper.appendChild(shape);wrapper.style.position='relative';var excludesBlocks=[125,331,554,746,754,776,778,786,858,896,897,924,915,943,951];if(excludesBlocks.indexOf(recordType)===-1){var firstDiv=wrapper.querySelector('div');firstDiv.style.cssText='position: relative; z-index: 1;';firstDiv.classList.add('t796_cont-near-shape-divider')}
var blocks=[195,279,675,694,734,823,938];if(blocks.indexOf(recordType)!==-1){shape.style.zIndex=1}
shape.style.display='block'}}
function t796__nextAll(element,selector){var nextElements=[];var nextElement=element;while(nextElement.nextElementSibling){nextElement=nextElement.nextElementSibling;if(nextElement.matches(selector)){nextElements.push(nextElement)}}
return nextElements}
function t796__prevAll(element,selector){var prevElements=[];var prevElement=element;while(prevElement.previousElementSibling){prevElement=prevElement.previousElementSibling;if(prevElement.matches(selector)){prevElements.push(prevElement)}}
return prevElements}
function t833_init(recid){t833_startAnimation(recid)}
function t833_showOnCertainWidth(el,wrapper){el.attr('class').split(' ').forEach(function(item){if(item.indexOf('t-screen')!==-1){wrapper.addClass(item)}})}
function t833_startAnimation(recid){var el=$('#rec'+recid);var wrapper=el.find('.t833__sliderwrapper');var wr=el.find('.t833');var recs=wr.attr('data-coverslider-rec-ids');t833_showOnCertainWidth(el,wrapper);if($('#allrecords').attr('data-tilda-mode')==='edit'){t833_addAnimation(el.find('.t833__demo'),wrapper);return}
if(typeof recs!=='undefined'){recs=recs.split(',');recs.forEach(function(rec){var curRec=$('#rec'+rec);var curWrapper=wrapper.clone().css('position','absolute');t833_addAnimation(curRec,curWrapper)})}else{var nextBlock=el.next(':has(.t-cover)');var prevBlock=el.prev(':has(.t-cover)');var curWrapper=wrapper.clone().css('position','absolute');if(nextBlock.length!==0){t833_addAnimation(nextBlock,curWrapper)}else if(prevBlock.length!==0){t833_addAnimation(prevBlock,curWrapper)}}}
function t833_addAnimation(curRec,wrapper){curRec.attr('data-animationappear','off').removeClass('r_hidden');var curRecType=curRec.attr('data-record-type');var isT941=curRecType==='941';var isT996=curRecType==='996';if(curRecType==='396'){curRec.find('.t396__filter').after(wrapper);wrapper.css('z-index','0')}
var coverWrapper;if(isT941){coverWrapper=curRec.find('.t941__cover-wrap')}else if(isT996){coverWrapper=curRec.find('.t996__cover-wrapper')}else{coverWrapper=curRec.find('.t-cover')}
if(coverWrapper.length>0){if(isT941){wrapper.addClass('t941__cover');coverWrapper.append(wrapper)}else if(isT996){wrapper.addClass('t996__cover');coverWrapper.append(wrapper)}else{coverWrapper.find('.t-cover__filter').after(wrapper)}
wrapper.css('z-index','0')}
var images=t833_createImageArr(wrapper);var imageCount=images.length;var imagesLoaded=0;for(var i=0;i<imageCount;i++){images[i].onload=function(){imagesLoaded++;if(imagesLoaded==imageCount&&curRec.length!==0){setTimeout(function(){t833_changeSlide(curRec)},3000)}}}
var slider=curRec.find('.t833__slider');var slide=curRec.find('.t833__slide');var numberOfSlides=slide.length;if(numberOfSlides===3||numberOfSlides===2){slide.clone().appendTo(slider)}}
function t833_createImageArr(wrapper){var imagesSrc=[];wrapper.find('.t833__slide').each(function(){imagesSrc.push($(this).attr('data-original'))});var images=[];imagesSrc.forEach(function(image,i){images[i]=new Image();images[i].src=image});return images}
function t833_changeSlide(curRec){var sliderWrapper=curRec.find('.t833__sliderwrapper');if(sliderWrapper.length){sliderWrapper.each(function(){var isLoaded=$(this).attr('data-loaded')&&$(this).attr('data-loaded')==='yes'?!0:!1;if(!isLoaded){var slide=$(this).find('.t833__slide');var firstSlide=$(this).find('.t833__slide:first-child');var numberOfSlides=slide.length;firstSlide.addClass('t833__slide_fx1');setTimeout(t833_kenBurns(slide,numberOfSlides,1),5000);$(this).attr('data-loaded','yes')}})}
function t833_kenBurns(slides,numberOfSlides,i){if(i==numberOfSlides){i=0}
$(slides[i]).addClass('t833__slide_fx');if(i===0){$(slides[numberOfSlides-2]).removeClass('t833__slide_fx t833__slide_fx1')}
if(i===1){$(slides[numberOfSlides-1]).removeClass('t833__slide_fx t833__slide_fx1');slides.removeClass('t833__slide_opacity')}
if(i>1){$(slides[i-2]).removeClass('t833__slide_fx t833__slide_fx1')}
setTimeout(function(){t833_kenBurns(slides,numberOfSlides,i+1)},5000)}}
function t875_init(recid){if(document.layers){document.captureEvents(Event.MOUSEDOWN)}
document.onmousedown=t875_click;document.oncontextmenu=function(event){var event=event||window.event;var sender=event.target||event.srcElement;if(sender&&(sender.tagName.match(/INPUT|TEXTAREA/i)||sender.hasAttribute('contenteditable')||(sender.parentElement&&sender.parentElement.hasAttribute('contenteditable')))){return}else{return!1}};t875_preventSelection(document);t875_preventUserSelect()}
function t875_preventUserSelect(){$('body').css({'-ms-user-select':'none','-moz-user-select':'none','-webkit-user-select':'none','user-select':'none','-webkit-touch-callout':'none'})}
function t875_click(event){t875_returnPrevent(event);if(document.all){if(event.button==2){return!1}}
if(document.layers){if(event.which==3){return!1}}}
function t875_preventSelection(element){var preventSelection=!1;t875_addHandler(element,'mousemove',function(){if(preventSelection){t875_removeSelection()}});t875_addHandler(element,'mousedown',function(event){var event=event||window.event;var sender=event.target||event.srcElement;preventSelection=sender&&!sender.tagName.match(/INPUT|TEXTAREA/i)&&!sender.hasAttribute('contenteditable')&&(sender.parentElement&&!sender.parentElement.hasAttribute('contenteditable'))});t875_addHandler(element,'mouseup',function(){if(preventSelection){t875_removeSelection()}
preventSelection=!1});t875_addHandler(element,'keydown',t875_killCtrlA);t875_addHandler(element,'keyup',t875_killCtrlA);t875_addHandler(element,'keydown',t875_killCtrlU);t875_addHandler(element,'keyup',t875_killCtrlU);t875_addHandler(element,'keydown',t875_killAltCmdI);t875_addHandler(element,'keyup',t875_killAltCmdI);t875_addHandler(element,'keydown',t875_killCtrlShiftI);t875_addHandler(element,'keyup',t875_killCtrlShiftI)}
function t875_addHandler(element,event,handler){if(element.attachEvent){element.attachEvent('on'+event,handler)}else if(element.addEventListener){element.addEventListener(event,handler,!1)}}
function t875_removeSelection(){if(window.getSelection){window.getSelection().removeAllRanges()}else if(document.selection&&document.selection.clear){document.selection.clear()}}
function t875_killCtrlU(event){t875_returnPrevent(event);var key=event.keyCode||event.which;if((event.ctrlKey&&key=='U'.charCodeAt(0))||(event.altKey&&event.metaKey&&(key=='U'.charCodeAt(0)||key=='u'.charCodeAt(0)))){if(event.preventDefault){event.preventDefault()}else{event.returnValue=!1}}}
function t875_killAltCmdI(event){t875_returnPrevent(event);var key=event.keyCode||event.which;if(event.altKey&&event.metaKey&&(key=='I'.charCodeAt(0)||key=='i'.charCodeAt(0))){if(event.preventDefault){event.preventDefault()}else{event.returnValue=!1}}}
function t875_killCtrlShiftI(event){t875_returnPrevent(event);var key=event.keyCode||event.which;if(event.shiftKey&&event.ctrlKey&&(key=='I'.charCodeAt(0)||key=='i'.charCodeAt(0))){if(event.preventDefault){event.preventDefault()}else{event.returnValue=!1}}}
function t875_killCtrlA(event){var event=event||window.event;var sender=event.target||event.srcElement;if(sender&&(sender.tagName.match(/INPUT|TEXTAREA|BUTTON/i)||sender.hasAttribute('contenteditable')||(sender.parentElement&&sender.parentElement.hasAttribute('contenteditable')))){return}
var key=event.keyCode||event.which;if((event.ctrlKey&&key=='A'.charCodeAt(0))||(event.metaKey&&key=='A'.charCodeAt(0))){t875_removeSelection();if(event.preventDefault){event.preventDefault()}else{event.returnValue=!1}}}
function t875_returnPrevent(event){var event=event||window.event;var sender=event.target||event.srcElement;if(sender&&(sender.tagName.match(/INPUT|TEXTAREA/i)||sender.hasAttribute('contenteditable')||(sender.parentElement&&sender.parentElement.hasAttribute('contenteditable')))){return}}
function t889_init(recId){var rec=document.getElementById('rec'+recId);var container=rec.querySelector('.t889');t889_setHeight(recId);window.addEventListener('resize',t_throttle(function(){if(window.noAdaptive&&window.noAdaptive===!0&&window.isMobile)return;t889_setHeight(recId)}));$(container).on('displayChanged',function(){t889_setHeight(recId)});if(window.isMobile){window.addEventListener('orientationchange',function(){t889_setHeight(recId)})}}
function t889_setHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t889');if(!container)return;var wrapper=rec.querySelector('.t889__wrapper');var imageWrap=rec.querySelector('.t889__blockimg');var image=imageWrap.querySelector('img');var content=rec.querySelector('.t889__content');var textWrapperHeight=t889_outerHeight(content);var newImage=new Image();var imageSrc=image.getAttribute('data-original')||image.getAttribute('src');newImage.src=imageSrc;newImage.addEventListener('load',function(){if(window.innerWidth>960){var imageStyle=getComputedStyle(imageWrap,null);var imagePaddingTop=parseInt(imageStyle.paddingTop)||0;var imagePaddingBottom=parseInt(imageStyle.paddingBottom)||0;var imageHeight=image.clientHeight-(imagePaddingTop+imagePaddingBottom);if(textWrapperHeight>=imageHeight){wrapper.style.height=textWrapperHeight+'px'}else{wrapper.style.height=imageHeight+'px'}}else{wrapper.style.height=null}})}
function t889_outerHeight(element){if(!element)return;var height=element.offsetHeight;var style=getComputedStyle(element);height+=parseInt(style.marginTop)+parseInt(style.marginBottom);return height}
function t923_init(recid){var el=$('#rec'+recid);t923_unifyHeights(recid);$(window).on('resize',t_throttle(function(){t923_unifyHeights(recid)}));el.find(".t923").on("displayChanged",function(){t923_unifyHeights(recid)});$(window).on('load',function(){t923_unifyHeights(recid)})}
function t923_unifyHeights(recid){var el=$('#rec'+recid);var cols=el.find(".t923__content");var maxHeight=0;cols.each(function(){var text=$(this).find(".t923__textwrapper");var btns=$(this).find(".t923__btn-wrapper, .t923__btntext-wrapper");var itemHeight=text.outerHeight()+btns.outerHeight();if(itemHeight>maxHeight){maxHeight=itemHeight}});cols.each(function(i,el){var height=$(el).css("height");if(height!==maxHeight+'px'){$(el).css("height",maxHeight)}});t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)})}
function t937_init(recid,styles){var rec=document.getElementById('rec'+recid);var playlist=rec.querySelector('.t937__playlist-wrap');var videoColumn=rec.querySelector('.t937__col_video');var videoData=t937_parseData(recid);var params=t937_getUrlParametrs(recid);var activeVideoId=params.activeVideoId;t937_setSizes(recid,styles);t937_renderVideoCount(videoData,recid,styles);t937_renderPlaylist(videoData,activeVideoId,recid,styles);t937_renderVideoFrame(videoData,activeVideoId,recid,styles);if(videoColumn)videoColumn.style.height='';if(playlist)playlist.style.visibility='visible';t937_addEvents(recid,styles)}
function t937_getUrlParametrs(recid){var activeRecId;var activeVideoId;var hash=window.location.hash;if(hash&&hash.indexOf('#tlection=')===-1){activeRecId=recid;activeVideoId=1}else{var params=hash.replace('#tlection=','').split('_');activeRecId=params[0];activeVideoId=+recid===+activeRecId?params[1]:1}
return{activeRecId:activeRecId,activeVideoId:activeVideoId,}}
function t937_parseData(recid){var rec=document.getElementById('rec'+recid);var recData=rec?rec.querySelector('.t937__data'):null;var data=recData?recData.innerHTML:'';var videos=[];if(data){data=data.replace(/&amp;/gi,'&');var segments=data.split('\n');for(var i=0;i<segments.length;i++){var segment=segments[i];var parts=segment.split(';');var video=t937_getVideoData(parts);if(video.url||video.section){videos.push(video)}}}
return videos}
function t937_getVideoData(data){var first=data[0].trim();if(first.indexOf('[')===0&&first.indexOf(']')===first.length-1){return{section:first.slice(1,-1),}}
var url=data[0]&&data[0].length?data[0].trim():null;var title=data[1]?data[1].trim():null;var time=data[2]?data[2].trim():null;var description=data[3]?data[3].trim():null;var type=null;if(/youtube.com|youtu.be/gi.test(url)){type='youtube'}
if(/vimeo.com/gi.test(url)){type='vimeo'}
return{url:url,title:title,time:time,description:description,type:type,}}
function t937_renderPlaylist(videoData,activeVideoId,recid,styles){var rec=document.getElementById('rec'+recid);var container=rec.querySelector('.t937__playlist');if(container)container.dataVideoContent=videoData;if(container)container.dataPlaylistStyles=styles;var videoCount=1;t937_setSizes(recid,styles);if(container)container.innerHTML='';var mainColor=styles.mainColor.length?'color: '+styles.mainColor+';':'';var secondaryColor=styles.secondaryColor.length?'color: '+styles.secondaryColor+';':'';var border=styles.borderColor.length?'border-bottom: 1px solid '+styles.borderColor+';':'';t937_renderFade(recid,styles.bgColor);for(var i=0;i<videoData.length;i++){var data=videoData[i];var id=i+1;var isActive=Number(id)===Number(activeVideoId);var item;if(Object.prototype.hasOwnProperty.call(data,'section')){item=document.createElement('div');item.classList.add('t937__playlist-item','t937__playlist-item_section');item.setAttribute('style',border);var itemChild=document.createElement('div');itemChild.classList.add('t937__playlist-section','t-name','t-name_xs');itemChild.setAttribute('style',mainColor);itemChild.textContent=data.section;item.insertAdjacentElement('beforeend',itemChild)}else{var title=data.title&&data.title.length?data.title:t937_translate('videoTitle');var time=data.time?data.time:'';var linkBgColor=isActive&&styles.linkBgColor.length?'background-color: '+styles.linkBgColor+';':'';item=document.createElement('div');item.classList.add('t937__playlist-item');item.setAttribute('data-video-id',id.toString());item.setAttribute('style',border);item.setAttribute('onclick','window.t937_onVideoClick('+id+', '+recid+')');var playlistLink=document.createElement('div');if(isActive){playlistLink.classList.add('t937__playlist-link','t-text','t-text_xs','t937__playlist-link_active')}else{playlistLink.classList.add('t937__playlist-link','t-text','t-text_xs')}
playlistLink.setAttribute('style',linkBgColor);var playlistNumber=document.createElement('div');playlistNumber.classList.add('t937__playlist-number');playlistNumber.setAttribute('style',secondaryColor);playlistNumber.textContent=videoCount.toString();var playlistTitle=document.createElement('div');playlistTitle.classList.add('t937__playlist-title');playlistTitle.setAttribute('style',mainColor);playlistTitle.textContent=title;var playlistTime=document.createElement('div');playlistTime.classList.add('t937__playlist-time');playlistTime.setAttribute('style',secondaryColor);playlistTime.textContent=time;playlistLink.insertAdjacentElement('beforeend',playlistNumber);playlistLink.insertAdjacentElement('beforeend',playlistTitle);playlistLink.insertAdjacentElement('beforeend',playlistTime);item.insertAdjacentElement('beforeend',playlistLink);item.addEventListener('mousemove',function(e){var currentItem=e.target.closest('.t937__playlist-item');currentItem.style.backgroundColor=styles.linkBgColor.length?styles.linkBgColor:'#F0F0F0'});item.addEventListener('mouseout',function(e){var currentItem=e.target.closest('.t937__playlist-item');currentItem.style.backgroundColor=''});videoCount++}
if(container)container.insertAdjacentElement('beforeend',item)}}
function t937_renderVideoFrame(data,activeVideoId,recid){var rec=document.getElementById('rec'+recid);var frame;var video;var container=rec?rec.querySelector('.t937__video'):null;var height=container?container.offsetWidth*0.5625:0;if(container)container.classList.remove('t937__video_empty');var id;for(var i=activeVideoId-1;i<data.length;i++){if(data[i].url){video=data[i];t937_renderDescription(video,recid);break}}
if(!data.length||!video||!video.type){if(container)container.classList.add('t937__video_empty');frame=document.createElement('div');frame.classList.add('t937__system-message');frame.textContent=!data.length?t937_translate('noData'):t937_translate('wrongFormat')}else if(video.type==='youtube'){var regex=/youtu(?:.*\/v\/|.*v\=|\.be\/)([A-Za-z0-9_\-]{11})/;id=video.url.match(regex);if(id!==null){id=id[1]}
frame=document.createElement('iframe');frame.classList.add('t937__video-frame','t937__video-frame_youtube');frame.width='100%';frame.height=height.toString();frame.src='https://www.youtube.com/embed/'+id+'?rel=0&fmt=18&html5=1&enablejsapi=1';frame.frameBorder='0';frame.setAttribute('allow','accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture');frame.setAttribute('allowfullscreen','')}else if(video.type==='vimeo'){var idMatch=/vimeo[^/]*\/(\d+)\/?(\w*)\/?/i.exec(video.url);id=idMatch?idMatch[1]:null;var hash=idMatch?'?h='+idMatch[2]:null;var timecodeMatch=/#t=(\d*h)?(\d*m)?\d*s$/i.exec(video.url);var timecode=timecodeMatch?'/'+timecodeMatch[0]:'';if(!id){if(container)container.classList.add('t937__video_empty');frame=document.createElement('div');frame.classList.add('t937__system-message');frame.textContent=t937_translate('wrongFormat')}else{frame=document.createElement('iframe');frame.classList.add('t937__video-frame','t937__video-frame_vimeo');frame.title='vimeo-player';frame.width='100%';frame.height=height.toString();frame.src='https://player.vimeo.com/video/'+id+hash+timecode;frame.frameBorder='0';frame.setAttribute('allowfullscreen','')}}
if(container){container.innerHTML='';container.insertAdjacentElement('beforeend',frame)}}
function t937_renderDescription(videoData,recid){var rec=document.getElementById('rec'+recid);var wrapper=rec?rec.querySelector('.t937__col_description'):null;var titleContainer=wrapper?wrapper.querySelector('.t937__video-title'):null;var descriptionContainer=wrapper?wrapper.querySelector('.t937__video-description'):null;if(wrapper)wrapper.classList.add('t937__col_hidden');if(titleContainer)titleContainer.innerHTML='';if(descriptionContainer)descriptionContainer.innerHTML='';if(!videoData.description)return;if(wrapper)wrapper.classList.remove('t937__col_hidden');var title=videoData.title&&videoData.title.length?videoData.title:t937_translate('videoTitle');var descriptionContent=t937_parseDescription(videoData.description);titleContainer.textContent=title;Array.prototype.forEach.call(descriptionContent,function(content){if(descriptionContainer)descriptionContainer.insertAdjacentElement('beforeend',content)})}
function t937_renderVideoCount(data,recid,styles){var rec=document.getElementById('rec'+recid);var subheading=rec?rec.querySelector('.t937__subheading-title'):null;var icon=rec?rec.querySelector('.t937__subheading-icon'):null;var size=0;var color=styles.secondaryColor.length?styles.secondaryColor.replace('#','%23'):'%23111111';if(icon)icon.style.backgroundImage='url("data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' viewBox=\'0 0 16 16\' width=\'16\' height=\'16\'%3E%3Ctitle%3Evideo playlist%3C/title%3E%3Cg class=\'nc-icon-wrapper\' stroke-width=\'1\' fill='+'\''+color+'\''+' stroke='+'\''+color+'\''+'%3E%3Crect x=\'0.5\' y=\'2.5\' width=\'15\' height=\'12\' rx=\'1\' fill=\'none\' stroke='+'\''+color+'\''+' stroke-linecap=\'round\' stroke-linejoin=\'round\'/%3E%3Cpolygon points=\'6.5 5.5 11.5 8.5 6.5 11.5 6.5 5.5\' fill=\'none\' stroke-linecap=\'round\' stroke-linejoin=\'round\' data-color=\'color-2\'/%3E%3Cline x1=\'3.5\' y1=\'0.5\' x2=\'12.5\' y2=\'0.5\' fill=\'none\' stroke='+'\''+color+'\''+' stroke-linecap=\'round\' stroke-linejoin=\'round\'/%3E%3C/g%3E%3C/svg%3E\"';for(var item in data){if(!data[item].section){size++}}
var videoPart=t937_translate('videoPart');if(subheading)subheading.textContent=size+' '+videoPart}
function t937_renderFade(recid,color){color=color.length?color:'#ffffff';var rec=document.getElementById('rec'+recid);var playlistFade=rec?rec.querySelector('.t937__playlist-fade'):null;var colorFrom=t937_hex2rgb(color,0);var colorTo=t937_hex2rgb(color,1);if(playlistFade)playlistFade.style.backgroundImage='linear-gradient('+colorFrom+' 0%, '+colorTo+' 90%)'}
function t937_parseDescription(string){var result=[];var parts=string.split('<br>');var res;parts.forEach(function(part){if(!part.length){res=document.createElement('br');result.push(res)}else{res=document.createElement('p');res.classList.add('t937__paragraph');res.innerHTML=part;result.push(res)}});return result}
function t937_setSizes(recid,styles){var rec=document.getElementById('rec'+recid);var playlistWrapper=rec?rec.querySelector('.t937__playlist-wrap'):null;var iframe=rec?rec.querySelector('.t937__video-frame'):null;var playlistCol=rec?rec.querySelector('.t937__col_playlist'):null;var description=rec?rec.querySelector('.t937__description'):null;var videoCol=rec?rec.querySelector('.t937__video'):null;var videoColWidth=videoCol?videoCol.offsetWidth:0;var height=videoColWidth*0.5625;if(iframe)iframe.setAttribute('height',height.toString());if(window.innerWidth>=960){if(description)description.style.width=videoColWidth+'px';if(playlistWrapper)playlistWrapper.style.height=height+'px';if(playlistWrapper)playlistWrapper.style.maxHeight='';if(styles.playlistWidth.length){if(playlistCol)playlistCol.style.width=parseInt(styles.playlistWidth,10)+'px'}}else{if(playlistWrapper)playlistWrapper.style.maxHeight=height+'px';if(playlistWrapper)playlistWrapper.style.height='';if(playlistCol)playlistCol.style.width='';if(description)description.style.width=''}}
function t937_translate(keyword){var dict=[];dict.videoTitle={RU:'Без названия',EN:'Untitled video',FR:'Vidéo sans titre',DE:'Video ohne Titel',ES:'Video sin título',PT:'Bez tytułu wideo',UK:'Відео без назви',JA:'無題の動画',ZH:'无标题的视频',PL:'Bez tytułu',};dict.videoPart={RU:'видео',EN:'videos',FR:'vidéos',DE:'videos',ES:'videos',PT:'filmy',UK:'відео',JA:'ビデオ',ZH:'影片',PL:'video',};dict.noData={RU:'Пожалуйста, добавьте хотя бы одно видео в плейлист',EN:'Please add at least one video to the playlist',UK:'Будь ласка, додайте хоча б одне відео в плейлист',PL:'Proszę dodać jeden filmik do listy',};dict.wrongFormat={RU:'Пожалуйста, проверьте корректность заполненных данных',EN:'Please check that the data is filled in correctly',UK:'Будь ласка, перевірте коректність заповнених даних',PL:'Sprawdź poprawność danych',};var lang=window.browserLang;if(dict[keyword]!==undefined){if(dict[keyword][lang]!==undefined&&dict[keyword][lang]!==''){return dict[keyword][lang]}else{return dict[keyword].EN}}
return 'Text not found #'+keyword}
function t937_hex2rgb(hex,opacity){var h=hex.replace('#','');h=h.match(new RegExp('(.{'+h.length/3+'})','g'));for(var i=0;i<h.length;i++){h[i]=parseInt(h[i].length===1?h[i]+h[i]:h[i],16)}
if(typeof opacity!='undefined'){h.push(opacity)}
return 'rgba('+h.join(',')+')'}
function t937_addEvents(recid,styles){window.addEventListener('resize',t_throttle(function(){t937_setSizes(recid,styles)}));if(typeof jQuery!=='undefined'){$('.t937').bind('displayChanged',function(){t937_setSizes(recid,styles)})}else{var currentBlocks=document.querySelectorAll('.t937');Array.prototype.forEach.call(currentBlocks,function(block){block.addEventListener('displayChanged',function(){t937_setSizes(recid,styles)})})}
var rec=document.getElementById('rec'+recid);var playlistWrap=rec?rec.querySelector('.t937__playlist-wrap'):null;var playlistFade=rec?rec.querySelector('.t937__playlist-fade'):null;if(playlistWrap){playlistWrap.addEventListener('scroll',function(){var currentHeight=playlistWrap.offsetHeight;var scrollTop=playlistWrap.scrollTop;var scrollHeight=playlistWrap.scrollHeight;var marginBottom=30;if(currentHeight+scrollTop>=scrollHeight-marginBottom){if(playlistFade)playlistFade.style.backgroundImage=''}else{t937_renderFade(recid,styles.bgColor)}})}}
function t937_onVideoClick(id,recid){var rec=document.getElementById('rec'+recid);var container=rec?rec.querySelector('.t937__playlist'):null;var videoData=container?container.dataVideoContent:null;var styles=container?container.dataPlaylistStyles:null;window.location.hash='tlection='+recid+'_'+id;t937_renderPlaylist(videoData,id,recid,styles);t937_renderVideoFrame(videoData,id,recid,styles);t937_playVideo(recid)}
function t937_playVideo(recid){var rec=document.getElementById('rec'+recid);var videoFrame=rec?rec.querySelector('.t937__video-frame'):null;if(videoFrame&&videoFrame.classList.contains('t937__video-frame_youtube')){videoFrame.addEventListener('load',function(){var command='playVideo';videoFrame.contentWindow.postMessage('{"event":"command","func":"'+command+'","args":""}','*')})}}